server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 333

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pdn.springcloud.entities

eureka:
  client:
    #是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置true才能陪着ribbon使用负责均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示IP地址
